# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/PETS',
                'doc_host': 'https://Brewer.github.io',
                'git_url': 'https://github.com/Brewer/PETS',
                'lib_path': 'PETS'},
  'syms': { 'PETS.core': { 'PETS.core.foo': ( 'https://Brewer.github.io/core.html#foo',
                                              'https://github.com/Brewer/PETS/blob/master/PETS/core.py#L7')},
            'PETS.test': { 'PETS.test.bar': ( 'https://Brewer.github.io/test.html#bar',
                                              'https://github.com/Brewer/PETS/blob/master/PETS/test.py#L7')}}}